config/routes.rb
SAPI::Application.routes.draw do
  devise_for :users, :controllers => { :passwords => "passwords", :registrations => "registrations", :sessions => "sessions" }
  as :user do
    get 'users/edit' => 'registrations#edit', :as => 'edit_user_registratione'
    put 'users' => 'registrations#update', :as => 'user_registration_update'
    post 'users' => 'registrations#create', :as => 'user_registration_create'
  end

  get 'mobile/terms_and_conditions' => 'mobile#terms_and_conditions'
  get 'mobile/privacy_policy' => 'mobile#privacy_policy'

  get 'about' => 'pages#about'
  get 'terms-of-use' => 'pages#terms_of_use'
  get 'eu_legislation' => 'pages#eu_legislation'
  get 'activities(/:start_week)' => 'activities#activities', as: :activities

  get 'admin/api_usage/overview' => 'admin/api_usage#index', :as => 'api_usage_overview'
  get 'admin/api_usage/user_overview/:id' => 'admin/api_usage#show', :as => 'api_user_usage'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  namespace :api do
    namespace :v1 do
      resources :taxon_concepts, :only => [:index, :show]
      resources :auto_complete_taxon_concepts, :only => [:index, :show]
      resources :geo_entities, :only => [:index]
      resources :terms, :only => [:index]
      resources :units, :only => [:index]
      resources :sources, :only => [:index]
      resources :purposes, :only => [:index]
      resources :trade_plus_filters, only: :index
      resources :eu_decisions, only: :index
      resources :documents do
        collection do
          get 'download_zip'
        end
      end
      resources :document_geo_entities, only: [:index]
      resources :events, only: [:index]
      resources :document_tags, only: [:index]
      get '/dashboard_stats/:iso_code' => 'dashboard_stats#index'
      resources :shipments, only: [:index]
      get '/shipments/chart' => 'shipments#chart_query'
      get '/shipments/grouped' => 'shipments#grouped_query'
      get '/shipments/over_time' => 'shipments#over_time_query'
      get '/shipments/aggregated_over_time' => 'shipments#aggregated_over_time_query'
      get '/shipments/country' => 'shipments#country_query'
      get '/shipments/search' => 'shipments#search_query'
      get '/shipments/download' => 'shipments#download_data'
      get '/shipments/search_download' => 'shipments#search_download_data'
      get '/shipments/search_download_all' => 'shipments#search_download_all_data'
    end
    resources :languages, :only => [:index]
    resources :users, :only => [:index]
    resources :designations, :only => [:index]
    resources :species_listings, :only => [:index]
    resources :change_types, :only => [:index]
    resources :ranks, :only => [:index]
    resources :geo_entities, :only => [:index]
    resources :geo_relationship_types, :only => [:index]
    resources :trade_downloads_cache_cleanup, only: [:index]
  end
  namespace :admin do
    resources :taxonomies, :only => [:index, :create, :update, :destroy]
    resources :terms, :only => [:index, :create, :update, :destroy]
    resources :sources, :only => [:index, :create, :update, :destroy]
    resources :purposes, :only => [:index, :create, :update, :destroy]
    resources :units, :only => [:index, :create, :update, :destroy]
    resources :taxon_concept_term_pairs, :only => [:index, :create, :update, :destroy]
    resources :term_trade_codes_pairs, :only => [:index, :create, :update, :destroy]
    resources :languages, :only => [:index, :create, :update, :destroy]
    resources :users
    resources :designations, :only => [:index, :create, :update, :destroy]
    resources :instruments, :only => [:index, :create, :update, :destroy]
    resources :species_listings, :only => [:index, :create, :update, :destroy]
    resources :change_types, :only => [:index, :create, :update, :destroy]
    resources :ranks, :only => [:index, :create, :update, :destroy]
    resources :tags, :only => [:index, :create, :update, :destroy]
    resources :eu_decision_types, :only => [:index, :create, :update, :destroy]
    resources :srg_histories, only: [:index, :create, :update, :destroy]
    resources :events do
      resource :document_batch, :only => [:new, :create]
      resources :documents, :only => [:index, :edit, :update, :destroy] do
        get :show_order, on: :collection, controller: :event_documents
        post :update_order, on: :collection, controller: :event_documents
      end
    end
    resources :eu_regulations do
      post :activate, :on => :member
      post :deactivate, :on => :member
      resources :listing_changes, :only => [:index, :destroy]
    end
    resources :eu_suspension_regulations do
      post :activate, :on => :member
      post :deactivate, :on => :member
      resources :eu_suspensions, :only => [:index, :destroy]
    end
    resources :eu_implementing_regulations
    resources :eu_council_regulations
    resources :cites_cops
    resources :cites_pcs
    resources :cites_acs
    resources :cites_tcs
    resources :ec_srgs
    resources :cites_extraordinary_meetings

    resource :document_batch, :only => [:new, :create]
    resources :documents do
      get :autocomplete, :on => :collection
    end

    resources :cites_suspension_notifications
    resources :references, :only => [:index, :create, :update, :destroy] do
      get :autocomplete, :on => :collection
    end
    resources :geo_entities, :only => [:index, :create, :update, :destroy] do
      resources :geo_relationships, :only => [:index, :create, :update, :destroy]
    end
    resources :cites_hash_annotations, :only => [:index, :create, :update, :destroy]
    resources :eu_hash_annotations, :only => [:index, :create, :update, :destroy]
    resources :cites_suspensions, :only => [:index, :new, :create, :edit, :update, :destroy]

    resources :quotas, :only => [:index, :destroy] do
      collection do
        get :duplication
        post :duplicate
        get :count
      end
    end

    resources :iucn_mappings, :only => [:index]
    resources :cms_mappings, :only => [:index]
    resources :ahoy_visits, :only => [:index, :show]
    resources :ahoy_events, :only => [:index, :show]

    resources :taxon_concepts do
      get :autocomplete, :on => :collection
      resources :children, :only => [:index]
      resources :taxon_relationships, :only => [:index, :create, :destroy]
      resources :comments, only: [:index, :create, :update],
        controller: :taxon_concept_comments
      resources :designations, :only => [] do
        resources :taxon_listing_changes, :as => :listing_changes
      end
      resources :taxon_commons, :only => [:new, :create, :edit, :update, :destroy]
      resources :distributions, :only => [:index, :new, :create, :edit, :update, :destroy]
      resources :synonym_relationships, :only => [:new, :create, :edit, :update, :destroy]
      resources :trade_name_relationships, :only => [:new, :create, :edit, :update, :destroy]
      resources :hybrid_relationships, :only => [:new, :create, :edit, :update, :destroy]
      resources :taxon_concept_references, :only => [:index, :new, :create, :destroy, :edit, :update]
      resources :names, :only => [:index]
      resources :eu_opinions, :only => [:index, :new, :create, :edit, :update, :destroy]

      resources :taxon_quotas, :only => [:index, :new, :create, :edit, :update, :destroy],
        :as => :quotas

      resources :taxon_eu_suspensions,
        :only => [:index, :new, :create, :edit, :update, :destroy],
        :as => :eu_suspensions

      resources :taxon_cites_suspensions,
        :only => [:index, :new, :create, :edit, :update, :destroy],
        :as => :cites_suspensions
      resources :taxon_instruments, :only => [:index, :new, :create, :edit, :update, :destroy]
    end
    resources :nomenclature_changes do
      resources :split, controller: 'nomenclature_changes/split'
      resources :lump, controller: 'nomenclature_changes/lump'
      resources :status_to_accepted,
        controller: 'nomenclature_changes/status_to_accepted'
      resources :status_to_synonym,
        controller: 'nomenclature_changes/status_to_synonym'
      resources :status_swap, controller: 'nomenclature_changes/status_swap'
    end
    get 'exports' => 'exports#index'
    get 'exports/download' => 'exports#download' # not sure about this, post??
    get 'stats' => 'statistics#index'
    root :to => 'taxon_concepts#index'
  end

  get 'trade/user_can_edit' => 'trade#user_can_edit'
  namespace :trade do
    resources :annual_report_uploads do
      resources :sandbox_shipments do
        collection do
          post :update_batch
          post :destroy_batch
        end
      end
      member do
        post 'submit'
      end
    end
    resources :validation_rules
    resources :validation_errors, only: [:update, :show]
    resources :shipments do
      collection do
        post :update_batch
        post :destroy_batch
        get :accepted_taxa_for_reported_taxon_concept
      end
    end
    resources :geo_entities, :only => [:index]
    resources :permits, :only => [:index]
    get 'exports/download' => 'exports#download'      # not sure about this, post??
    get 'exports/download_stats' => 'exports#download_stats', :as => :trade_download_stats
    get 'stats' => 'statistics#index'
    get 'summary_year' => 'statistics#summary_year'
    get 'summary_creation' => 'statistics#summary_creation'
    get 'trade_transactions' => 'statistics#trade_transactions'
    root :to => 'ember#start'
  end

  namespace :species do
    get 'exports' => 'exports#index'
    get 'exports/download' => 'exports#download' # not sure about this, post??
    get '*foo' => 'ember#start'
    root :to => 'ember#start'
  end

  namespace :checklist do
    resources :geo_entities, :only => [:index] # TODO: move to API
    resources :downloads do
      member do
        get :download
      end
      collection do
        get :download_index
        get :download_history
      end
    end

app/controllers/admin/taxon_quotas_controller.rb
class Admin::TaxonQuotasController < Admin::SimpleCrudController
  defaults :resource_class => Quota,
    :collection_name => 'quotas', :instance_name => 'quota'
  belongs_to :taxon_concept

  before_filter :load_lib_objects
  before_filter :load_search, :except => [:destroy]
  layout 'taxon_concepts'

  authorize_resource :class => false

  def update
    update! do |success, failure|
      success.html {
        redirect_to admin_taxon_concept_quotas_url(params[:taxon_concept_id]),
        :notice => 'Operation successful'
      }
      failure.html {
        load_lib_objects
        render 'new'
      }

      success.js { render 'create' }
      failure.js {
        load_lib_objects
        render 'new'
      }
    end
  end

  def create
    create! do |success, failure|
      success.html {
        redirect_to admin_taxon_concept_quotas_url(params[:taxon_concept_id]),
        :notice => 'Operation successful'
      }
      failure.html { render 'create' }
    end
  end

  def destroy
    destroy! do |success, failure|
      success.html {
        redirect_to admin_taxon_concept_quotas_url(@taxon_concept),
        :notice => 'Operation successful'
      }
    end
  end

  protected

  def load_lib_objects
    @units = Unit.order(:code)
    @terms = Term.order(:code)
    @sources = Source.order(:code)
    @purposes = Purpose.order(:code)
    @geo_entities = GeoEntity.order(:name_en).joins(:geo_entity_type).
      where(:is_current => true,
            :geo_entity_types => { :name => GeoEntityType::SETS[GeoEntityType::DEFAULT_SET] })
  end

  def collection
    @quotas ||= end_of_association_chain.
      joins(:geo_entity).
      order('start_date DESC, geo_entities.name_en ASC,
        notes ASC').
      page(params[:page])
  end
end

app/views/admin/taxon_quotas/_current_quotas_form.html.erb
<% if @taxon_concept.current_quotas.count > 0 %>
  <table class="quota table table-bordered table-striped">
    <thead>
      <th>Quota</th>
      <th>Year</th>
      <th>Published at</th>
      <th>Country or Territory</th>
      <th>Notes</th>
      <th>Current</th>
    </thead>

    <tbody>
    <% @taxon_concept.current_quotas.each do |quota| %>

      <tr>
        <td><%= quota.quota %> <%= quota.unit.try(:code) %></td>
        <td><%= quota.year %></td>
        <td><%= quota.publication_date_formatted %></td>
        <td><%= quota.geo_entity && quota.geo_entity.iso_code2 %></td>
        <td><%= quota.notes %></td>
        <td>
          <%= form_for [:admin, @taxon_concept, quota], :remote => true do |f| %>
            <%= f.check_box :is_current %>
          <% end %>
        </td>
      </tr>

    <% end %>
    </tbody>
  </table>
<% end %>

app/views/admin/taxon_quotas/_form.html.erb
<%= admin_new_modal({:title => "Current CITES Quotas"}) {
  render :partial => "current_quotas_form",
    :locals => {:current_quotas => @taxon_concept.current_quotas}
} %>

<%= nested_form_for [:admin, @taxon_concept, @quota], :html => {:class => 'form-horizontal'} do |f| %>

  <p>
    <%= link_to("View Current Quotas", "#new-quota",
      {
        :role => "button",
        :"data-toggle" => "modal",
      }) %>
  </p>

  <%= error_messages_for(@quota) %>

  <div class="control-group">
    <%= f.label :quota, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :quota, :value => @quota.quota %>
      <%= f.select :unit_id,
        options_from_collection_for_select(@units, :id, :code, @quota.unit_id),
        { :include_blank => true },
        {:class => 'quota select2', :style => 'width: 220px' }
      %>
      <span class="help-block">For quotas <strong>in prep</strong>aration use <strong>-1</strong> for quota value.</span>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :publication_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :publication_date, :class => "quota datepicker", :value => @quota.publication_date_formatted %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :geo_entity_id, "Country or Territory", :class => 'control-label' %>
    <div class="controls">
      <%= f.select :geo_entity_id,
        options_from_collection_for_select(
          @geo_entities,
          :id,
          :name_en,
          @quota.geo_entity_id
      ),
        { :include_blank => true },
        {:class => 'quota select2', :style => 'width: 220px' }
      %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">Validity</label>
    <div class="controls">
      <%= f.text_field :start_date, :class => "quota datepicker", :value => @quota.start_date_formatted, :placeholder => 'Start Date' %>
      <%= f.text_field :end_date, :class => "quota datepicker", :value => @quota.end_date_formatted, :placeholder => 'End Date' %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">Notes</label>
    <div class="controls">
      <%= f.text_area :notes, :class => 'quota', :value => @quota.notes %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">Internal notes</label>
    <div class="controls">
      <%= f.text_area :internal_notes, :class => 'quota', :value => @quota.internal_notes %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :term_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :term_ids,
        options_from_collection_for_select(@terms, :id, :code, @quota.term_ids),
        { :include_blank => true },
        {:class => 'quota select2', :multiple => true, :style => 'width: 220px' }
      %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :source_id, :class => 'control-label'  %>
    <div class="controls">
      <%= f.select :source_ids,
        options_from_collection_for_select(@sources, :id, :code, @quota.source_ids),
        { :include_blank => true},
        {:class => 'quota select2', :multiple => true, :style => 'width: 220px' }
      %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :url, "URL", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :url, :class => 'quota', :value => @quota.url %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :is_current, "Is current?", :class => 'control-label'%>
    <div class="controls">
      <%= f.check_box :is_current, :value => @quota.is_current %><br>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :public_display, "Display publicly?", :class => 'control-label'%>
    <div class="controls">
      <%= f.check_box :public_display, :value => @quota.public_display %><br>
    </div>
  </div>

  <%= render :partial => 'admin/shared/nomenclature_notes_form',
    locals: {
      f: f,
      locale_columns: Quota.locale_columns(:nomenclature_note)
    }
  %>

  <p class="pull-right">
    <%= link_to 'Cancel', admin_taxon_concept_quotas_path(@taxon_concept),
      :class => "btn" %>
    <%= f.submit "Save", :class => "btn btn-primary save-button" %>
  </p>
<% end %>

app/views/admin/taxon_quotas/_list.html.erb
<thead>
  <th>Year</th>
  <th>Country or Territory</th>
  <th>Quantity</th>
  <th>Unit</th>
  <th>Term</th>
  <th>Source</th>
  <th>Notes</th>
  <th>Date</th>
  <th>Public display?</th>
  <th>Actions</th>
  <th>Info</th>
</thead>
<tbody>
  <% collection.each do |quota| -%>
    <tr class="<%= if quota.is_current? then "current_listing" end %>">
      <td><%= quota.year %></td>
      <td><%= quota.geo_entity && quota.geo_entity.name_en %></td>
      <td>
        <% if quota.quota == -1 %>
          in preparation
        <% else %>
          <%= quota.quota %>
        <% end %>
      </td>
      <td><%= quota.unit.try(:code) %></td>
      <td><%= quota.terms && quota.terms.map(&:code).join(', ') %></td>
      <td><%= quota.sources && quota.sources.map(&:code).join(', ') %></td>
      <td><%= quota.notes %></td>
      <td><%= quota.publication_date_formatted %></td>
      <td><%= true_false_icon(quota.public_display) %></td>
      <td>
        <%= link_to edit_icon,
          edit_admin_taxon_concept_quota_path(@taxon_concept, quota)
        %>
        <%= link_to delete_icon,
          admin_taxon_concept_quota_path(@taxon_concept, quota),
          data: { confirm: "Warning: you are about to delete data. Are you sure?" }, :method => :delete
        %>
      </td>
      <td>
        <%= tracking_info(quota) %>
        <%= internal_notes(quota) %>
      </td>
    </tr>
  <% end -%>
</tbody>

app/views/admin/taxon_quotas/edit.html.erb
<%= render('form') %>

app/views/admin/taxon_quotas/index.html.erb
<div class="admin-header">
  <h3>CITES Quotas</h3>
  <div class="action-buttons">
    <%= admin_add_new_button(
      :resource => 'quota',
      :href => new_admin_taxon_concept_quota_url(@taxon_concept),
      :"data-toggle" => nil,
      :role => nil
    ) %>
  </div>
</div>

<%= admin_new_modal{ '' } %>

<%= admin_table %>

<%= paginate collection %>

app/views/admin/taxon_quotas/new.html.erb
<%= render('form') %>

app/views/admin/taxon_quotas/new.js.erb
$('#admin-new-<%= controller_name.singularize %>-form').html("<%= escape_javascript(render('form')) %>");
$('#new-<%= controller_name.singularize %>').modal('show');
window.adminEditor.initForm();