config/routes.rb
SAPI::Application.routes.draw do
  devise_for :users, :controllers => { :passwords => "passwords", :registrations => "registrations", :sessions => "sessions" }
  as :user do
    get 'users/edit' => 'registrations#edit', :as => 'edit_user_registratione'
    put 'users' => 'registrations#update', :as => 'user_registration_update'
    post 'users' => 'registrations#create', :as => 'user_registration_create'
  end

  get 'mobile/terms_and_conditions' => 'mobile#terms_and_conditions'
  get 'mobile/privacy_policy' => 'mobile#privacy_policy'

  get 'about' => 'pages#about'
  get 'terms-of-use' => 'pages#terms_of_use'
  get 'eu_legislation' => 'pages#eu_legislation'
  get 'activities(/:start_week)' => 'activities#activities', as: :activities

  get 'admin/api_usage/overview' => 'admin/api_usage#index', :as => 'api_usage_overview'
  get 'admin/api_usage/user_overview/:id' => 'admin/api_usage#show', :as => 'api_user_usage'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  namespace :api do
    namespace :v1 do
      resources :taxon_concepts, :only => [:index, :show]
      resources :auto_complete_taxon_concepts, :only => [:index, :show]
      resources :geo_entities, :only => [:index]
      resources :terms, :only => [:index]
      resources :units, :only => [:index]
      resources :sources, :only => [:index]
      resources :purposes, :only => [:index]
      resources :trade_plus_filters, only: :index
      resources :eu_decisions, only: :index
      resources :documents do
        collection do
          get 'download_zip'
        end
      end
      resources :document_geo_entities, only: [:index]
      resources :events, only: [:index]
      resources :document_tags, only: [:index]
      get '/dashboard_stats/:iso_code' => 'dashboard_stats#index'
      resources :shipments, only: [:index]
      get '/shipments/chart' => 'shipments#chart_query'
      get '/shipments/grouped' => 'shipments#grouped_query'
      get '/shipments/over_time' => 'shipments#over_time_query'
      get '/shipments/aggregated_over_time' => 'shipments#aggregated_over_time_query'
      get '/shipments/country' => 'shipments#country_query'
      get '/shipments/search' => 'shipments#search_query'
      get '/shipments/download' => 'shipments#download_data'
      get '/shipments/search_download' => 'shipments#search_download_data'
      get '/shipments/search_download_all' => 'shipments#search_download_all_data'
    end
    resources :languages, :only => [:index]
    resources :users, :only => [:index]
    resources :designations, :only => [:index]
    resources :species_listings, :only => [:index]
    resources :change_types, :only => [:index]
    resources :ranks, :only => [:index]
    resources :geo_entities, :only => [:index]
    resources :geo_relationship_types, :only => [:index]
    resources :trade_downloads_cache_cleanup, only: [:index]
  end
  namespace :admin do
    resources :taxonomies, :only => [:index, :create, :update, :destroy]
    resources :terms, :only => [:index, :create, :update, :destroy]
    resources :sources, :only => [:index, :create, :update, :destroy]
    resources :purposes, :only => [:index, :create, :update, :destroy]
    resources :units, :only => [:index, :create, :update, :destroy]
    resources :taxon_concept_term_pairs, :only => [:index, :create, :update, :destroy]
    resources :term_trade_codes_pairs, :only => [:index, :create, :update, :destroy]
    resources :languages, :only => [:index, :create, :update, :destroy]
    resources :users
    resources :designations, :only => [:index, :create, :update, :destroy]
    resources :instruments, :only => [:index, :create, :update, :destroy]
    resources :species_listings, :only => [:index, :create, :update, :destroy]
    resources :change_types, :only => [:index, :create, :update, :destroy]
    resources :ranks, :only => [:index, :create, :update, :destroy]
    resources :tags, :only => [:index, :create, :update, :destroy]
    resources :eu_decision_types, :only => [:index, :create, :update, :destroy]
    resources :srg_histories, only: [:index, :create, :update, :destroy]
    resources :events do
      resource :document_batch, :only => [:new, :create]
      resources :documents, :only => [:index, :edit, :update, :destroy] do
        get :show_order, on: :collection, controller: :event_documents
        post :update_order, on: :collection, controller: :event_documents
      end
    end
    resources :eu_regulations do
      post :activate, :on => :member
      post :deactivate, :on => :member
      resources :listing_changes, :only => [:index, :destroy]
    end
    resources :eu_suspension_regulations do
      post :activate, :on => :member
      post :deactivate, :on => :member
      resources :eu_suspensions, :only => [:index, :destroy]
    end
    resources :eu_implementing_regulations
    resources :eu_council_regulations
    resources :cites_cops
    resources :cites_pcs
    resources :cites_acs
    resources :cites_tcs
    resources :ec_srgs
    resources :cites_extraordinary_meetings

    resource :document_batch, :only => [:new, :create]
    resources :documents do
      get :autocomplete, :on => :collection
    end

    resources :cites_suspension_notifications
    resources :references, :only => [:index, :create, :update, :destroy] do
      get :autocomplete, :on => :collection
    end
    resources :geo_entities, :only => [:index, :create, :update, :destroy] do
      resources :geo_relationships, :only => [:index, :create, :update, :destroy]
    end
    resources :cites_hash_annotations, :only => [:index, :create, :update, :destroy]
    resources :eu_hash_annotations, :only => [:index, :create, :update, :destroy]
    resources :cites_suspensions, :only => [:index, :new, :create, :edit, :update, :destroy]

    resources :quotas, :only => [:index, :destroy] do
      collection do
        get :duplication
        post :duplicate
        get :count
      end
    end

    resources :iucn_mappings, :only => [:index]
    resources :cms_mappings, :only => [:index]
    resources :ahoy_visits, :only => [:index, :show]
    resources :ahoy_events, :only => [:index, :show]

    resources :taxon_concepts do
      get :autocomplete, :on => :collection
      resources :children, :only => [:index]
      resources :taxon_relationships, :only => [:index, :create, :destroy]
      resources :comments, only: [:index, :create, :update],
        controller: :taxon_concept_comments
      resources :designations, :only => [] do
        resources :taxon_listing_changes, :as => :listing_changes
      end
      resources :taxon_commons, :only => [:new, :create, :edit, :update, :destroy]
      resources :distributions, :only => [:index, :new, :create, :edit, :update, :destroy]
      resources :synonym_relationships, :only => [:new, :create, :edit, :update, :destroy]
      resources :trade_name_relationships, :only => [:new, :create, :edit, :update, :destroy]
      resources :hybrid_relationships, :only => [:new, :create, :edit, :update, :destroy]
      resources :taxon_concept_references, :only => [:index, :new, :create, :destroy, :edit, :update]
      resources :names, :only => [:index]
      resources :eu_opinions, :only => [:index, :new, :create, :edit, :update, :destroy]

      resources :taxon_quotas, :only => [:index, :new, :create, :edit, :update, :destroy],
        :as => :quotas

      resources :taxon_eu_suspensions,
        :only => [:index, :new, :create, :edit, :update, :destroy],
        :as => :eu_suspensions

      resources :taxon_cites_suspensions,
        :only => [:index, :new, :create, :edit, :update, :destroy],
        :as => :cites_suspensions
      resources :taxon_instruments, :only => [:index, :new, :create, :edit, :update, :destroy]
    end
    resources :nomenclature_changes do
      resources :split, controller: 'nomenclature_changes/split'
      resources :lump, controller: 'nomenclature_changes/lump'
      resources :status_to_accepted,
        controller: 'nomenclature_changes/status_to_accepted'
      resources :status_to_synonym,
        controller: 'nomenclature_changes/status_to_synonym'
      resources :status_swap, controller: 'nomenclature_changes/status_swap'
    end
    get 'exports' => 'exports#index'
    get 'exports/download' => 'exports#download' # not sure about this, post??
    get 'stats' => 'statistics#index'
    root :to => 'taxon_concepts#index'
  end

  get 'trade/user_can_edit' => 'trade#user_can_edit'
  namespace :trade do
    resources :annual_report_uploads do
      resources :sandbox_shipments do
        collection do
          post :update_batch
          post :destroy_batch
        end
      end
      member do
        post 'submit'
      end
    end
    resources :validation_rules
    resources :validation_errors, only: [:update, :show]
    resources :shipments do
      collection do
        post :update_batch
        post :destroy_batch
        get :accepted_taxa_for_reported_taxon_concept
      end
    end
    resources :geo_entities, :only => [:index]
    resources :permits, :only => [:index]
    get 'exports/download' => 'exports#download'      # not sure about this, post??
    get 'exports/download_stats' => 'exports#download_stats', :as => :trade_download_stats
    get 'stats' => 'statistics#index'
    get 'summary_year' => 'statistics#summary_year'
    get 'summary_creation' => 'statistics#summary_creation'
    get 'trade_transactions' => 'statistics#trade_transactions'
    root :to => 'ember#start'
  end

  namespace :species do
    get 'exports' => 'exports#index'
    get 'exports/download' => 'exports#download' # not sure about this, post??
    get '*foo' => 'ember#start'
    root :to => 'ember#start'
  end

  namespace :checklist do
    resources :geo_entities, :only => [:index] # TODO: move to API
    resources :downloads do
      member do
        get :download
      end
      collection do
        get :download_index
        get :download_history
      end
    end

app/models/trade_code.rb
# == Schema Information
#
# Table name: trade_codes
#
#  id         :integer          not null, primary key
#  code       :string(255)      not null
#  name_en    :string(255)      not null
#  type       :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  name_es    :string(255)
#  name_fr    :string(255)
#

class TradeCode < ActiveRecord::Base
  attr_accessible :code, :type,
    :name_en, :name_es, :name_fr
  translates :name

  validates :code, :presence => true, :uniqueness => { :scope => :type }

  def self.search(query)
    if query.present?
      where("UPPER(code) LIKE UPPER(:query)
            OR UPPER(name_en) LIKE UPPER(:query)
            OR UPPER(name_fr) LIKE UPPER(:query)
            OR UPPER(name_es) LIKE UPPER(:query)",
            :query => "%#{query}%")
    else
      all
    end
  end

end

app/helpers/admin/trade_codes_helper.rb
module Admin::TradeCodesHelper
  def sub_nav
    content_tag(:ul, :class => "nav nav-pills") do
      ["purposes", "sources", "terms", "units"].each do |subclass|
        concat(content_tag(:li, :class => "#{controller_name == subclass ? 'active' : ''}") do
          link_to subclass.titleize, send("admin_#{subclass}_path")
        end)
      end
    end
  end
end

app/views/admin/trade_codes/_form.html.erb
<%= form_for resource_instance_name, :url => collection_url, :remote => true do |f| %>

  <%= error_messages_for(resource_instance_name) %>

  <label>Code</label><%= f.text_field :code %><br />
  <p>Name</p>
  <label>EN</label> <%= f.text_field :name_en %><br />
  <label>ES</label> <%= f.text_field :name_es %><br />
  <label>FR</label> <%= f.text_field :name_fr %><br />
<% end %>

app/views/admin/trade_codes/_list.html.erb
<thead>
  <th width="7%">Code</th>
  <th width="15%">Name (EN)</th>
  <th width="15%">Name (ES)</th>
  <th width="15%">Name (FR)</th>
  <th width="10%">Actions</th>
</thead>
<tbody>
  <% collection.each do |trade_code| -%>
    <tr>
      <td>
        <a href="#" class="editable editable-click editable-required" data-type="text" data-resource="<%= controller_name.singularize %>" data-name="code"
          data-placeholder="Required" data-original-title="Enter the code"
          data-url="<%= resource_url(trade_code) %>" data-pk="<%= trade_code.id %>">
          <%= trade_code.code %>
        </a>
      </td>
      <td>
        <a href="#" class="editable editable-click editable-required" data-type="text" data-resource="<%= controller_name.singularize %>" data-name="name_en"
          data-placeholder="Required" data-original-title="Enter the name in English"
          data-url="<%= resource_url(trade_code) %>" data-pk="<%= trade_code.id %>">
          <%= trade_code.name_en %>
        </a>
      </td>
      <td>
        <a href="#" class="editable editable-click" data-type="text" data-resource="<%= controller_name.singularize %>" data-name="name_es"
          data-placeholder="Required" data-original-title="Enter the name in Spanish"
          data-url="<%= resource_url(trade_code) %>" data-pk="<%= trade_code.id %>">
          <%= trade_code.name_es %>
        </a>
      </td>
      <td>
        <a href="#" class="editable editable-click" data-type="text" data-resource="<%= controller_name.singularize %>" data-name="name_fr"
          data-placeholder="Required" data-original-title="Enter the name in French"
          data-url="<%= resource_url(trade_code) %>" data-pk="<%= trade_code.id %>">
          <%= trade_code.name_fr %>
        </a>
      </td>
      <td>
        <%= link_to delete_icon, resource_url(trade_code), data: { confirm: "Warning: you are about to delete data. Are you sure?" }, :method => :delete %>
      </td>
    </tr>
  <% end -%>
</tbody>

app/views/admin/trade_codes/create.js.erb
$('.modal').modal('hide');
$('#admin-in-place-editor').html("<%= escape_javascript(render('admin/trade_codes/list')) %>");
window.adminEditor.init();
window.adminEditor.alertSuccess("Operation successful");

app/views/admin/trade_codes/index.html.erb
<%= admin_title %>

<%= sub_nav %>

<%= admin_new_modal do %>
  <%= render :partial => 'admin/trade_codes/form' %>
<% end %>

<%= admin_simple_search %>

<%= admin_table do %>
  <%=
    render :partial => 'admin/trade_codes/list',
    :locals => {:collection => collection}
  %>
<% end %>

<%= paginate collection %>

app/views/admin/trade_codes/new.js.erb
$('#admin-new-<%= controller_name.singularize %>-form').html("<%= escape_javascript(render('admin/trade_codes/form')) %>");